[project]
name = "5th-assign"
version = "0.1.0"
description = "A project based on multiple steps of agents to evaluate tool"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "openai-agents>=0.0.9",
    "pydantic>=2.11.2",
    "python-dotenv>=1.1.0",
]
